# Generated by Django 5.0.4 on 2024-04-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='charge',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='end_time',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='start_time',
            field=models.TimeField(default='08:00'),
        ),
    ]
