# Generated by Django 5.0.4 on 2024-04-30 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_department_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='location',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='details.location'),
            preserve_default=False,
        ),
    ]
