# Generated by Django 5.0.4 on 2024-04-17 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_doctor_charge_doctor_end_time_doctor_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('booking_time', models.TimeField(verbose_name='Booking Time')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.doctor')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='details.doctor')),
            ],
        ),
    ]
