# Generated by Django 5.0.4 on 2024-04-17 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='department',
        ),
        migrations.AlterField(
            model_name='booking',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.doctor'),
        ),
    ]
