# Generated by Django 5.0.4 on 2024-05-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_hospital_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='location',
        ),
    ]
