# Generated by Django 5.0.4 on 2024-05-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Visited', 'Visited'), ('Expired', 'Expired')], default='Pending', max_length=50),
        ),
    ]
