# Generated by Django 5.0.4 on 2024-05-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_department_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='pic',
            field=models.ImageField(default='default_image.jpg', upload_to='docimg'),
        ),
    ]
