# Generated by Django 5.0.4 on 2024-05-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_image.jpg', upload_to='homeimg')),
            ],
        ),
    ]
