# Generated by Django 5.0.2 on 2024-08-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_banner_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location_Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='defualt_image.jpg', upload_to='location_img')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
    ]
