# Generated by Django 5.0.2 on 2024-08-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_location_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crd_img', models.ImageField(upload_to='main_crd_img')),
                ('title', models.CharField(max_length=50)),
                ('discription', models.CharField(max_length=50)),
                ('button', models.CharField(max_length=50)),
            ],
        ),
    ]
