# Generated by Django 5.0.4 on 2024-05-04 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
