# Generated by Django 5.0.2 on 2024-08-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0008_main_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner_cards',
            name='title',
            field=models.CharField(default='no title', max_length=500),
        ),
    ]
