# Generated by Django 5.0.4 on 2024-05-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0009_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='slot',
            field=models.IntegerField(default=20),
        ),
    ]
