# Generated by Django 5.0.2 on 2024-08-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0010_main_cards_button_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_cards',
            name='click_url',
            field=models.URLField(default='/indian'),
        ),
    ]
